name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker
      uses: docker/build-push-action@v3
      with:
        context: ./
        load: true
        tags: cuzfrog/oracle-xe:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Set image tag as env
      run: |
        VERSION=18sip
        echo "IMAGE=cuzfrog/oracle-xe:$VERSION" >> $GITHUB_ENV

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: cuzfrog
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push Docker
      uses: docker/build-push-action@v3
      with:
        context: ./
        push: true
        tags: cuzfrog/oracle-xe:latest,${{ env.IMAGE }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
